debug = true 
project = "rain"

[[redis]]
disable = true
name = "test-redis"
addr = "redis://password@127.0.0.1:6379"

[[database]]
disable = true
name = "test-mysql"
type = "mysql"
addr = "user:password@tcp(127.0.01:3306)/?charset=utf8mb4&interpolateParams=true"

[worker]
capacity = 1000

[custom]
test_key = "test_value"
